name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      POUDRIERE_JAIL : "14.1-RELEASE"
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        envs: 'MYTOKEN2 POUDRIERE_JAIL'
        usesh: true
        run: |
          #pwd
          #ls -lah
          #whoami
          #env
          freebsd-version
          #gpart list

          ###### Configure & setup ZFS ######
          kldload zfs
          sysrc -f /boot/loader.conf zfs_load="YES"
          sysrc zfs_enable="YES"

          truncate -s 10G /home/runner/zpool.disk
          zpool create -O atime=off -f zroot /home/runner/zpool.disk
          #zpool create -O atime=off zroot ada1

          ###### Configure Poudriere ######
          echo "ZPOOL=zroot" > /usr/local/etc/poudriere.conf
          echo "BASEFS=/usr/local/poudriere" >> /usr/local/etc/poudriere.conf
          echo "DISTFILES_CACHE=/usr/ports/distfiles" >> /usr/local/etc/poudriere.conf
          echo "RESOLV_CONF=/etc/resolv.conf" >> /usr/local/etc/poudriere.conf
          pkg install -y poudriere git
          mkdir -p /usr/ports/distfiles
          poudriere jail -c -j port-tester -v $POUDRIERE_JAIL
          poudriere ports -c -p development

          ###### Build Kleened #######
          git clone https://github.com/kleene-project/ports.git
          #cp -r /home/runner/work/ports/sysutils/kleene-daemon /usr/local/poudriere/ports/development/sysutils/
          cp -r /home/runner/work/test-gh-action/test-gh-action/ports/sysutils/kleene-daemon /usr/local/poudriere/ports/development/sysutils/
          poudriere testport -j port-tester -p development -o sysutils/kleene-daemon
          poudriere bulk -j port-tester -p development sysutils/kleene-daemon
