name: Build pkg-package and create a new release if needed

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and publish a pkg package of Kleened
    env:
      POUDRIERE_JAIL : "14.1-RELEASE"
    permissions:
      # Needed when creating releases
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build test-package in FreeBSD
      id: kleened-pkg-build
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        envs: 'POUDRIERE_JAIL'
        usesh: true
        run: |
          #env
          freebsd-version

          ###### Configure ZFS ######
          kldload zfs
          sysrc -f /boot/loader.conf zfs_load="YES"
          sysrc zfs_enable="YES"

          truncate -s 10G /home/runner/zpool.disk
          zpool create -O atime=off -f zroot /home/runner/zpool.disk

          ###### Install & configure Poudriere ######
          echo "ZPOOL=zroot" > /usr/local/etc/poudriere.conf
          echo "BASEFS=/usr/local/poudriere" >> /usr/local/etc/poudriere.conf
          echo "DISTFILES_CACHE=/usr/ports/distfiles" >> /usr/local/etc/poudriere.conf
          echo "RESOLV_CONF=/etc/resolv.conf" >> /usr/local/etc/poudriere.conf
          pkg install -y poudriere git
          mkdir -p /usr/ports/distfiles
          poudriere jail -c -j port-tester -v $POUDRIERE_JAIL
          poudriere ports -c -p development

          ###### Build Kleened #######
          git clone https://github.com/kleene-project/ports.git
          #cp -r /home/runner/work/ports/sysutils/kleene-daemon /usr/local/poudriere/ports/development/sysutils/
          cp -r /home/runner/work/test-gh-action/test-gh-action/ports/sysutils/kleene-daemon /usr/local/poudriere/ports/development/sysutils/
          poudriere testport -j port-tester -p development -o sysutils/kleene-daemon
          poudriere bulk -j port-tester -p development sysutils/kleene-daemon

          cp /usr/local/poudriere/data/packages/port-tester-development/All/kleene-daemon-*.pkg .

          ### used for testing:
          #echo "lol" > kleene-daemon-0.1.0.r2.pkg

          ###### Copy package into workdir and save filename #######
          PKG_FILE=$(ls kleene-daemon-*)
          PKG_FILE_TRIM=${PKG_FILE%.pkg}
          NEW_PKG_FILE=${PKG_FILE_TRIM}-freebsd14.pkg
          mv ${PKG_FILE} ${NEW_PKG_FILE}
          echo "PKG_FILE=${NEW_PKG_FILE}" >> "$GITHUB_ENV"
          echo "PKG_FILE=${NEW_PKG_FILE}" >> "$GITHUB_OUTPUT"

    - name: Create artifact from the kleened pkg package
      uses: actions/upload-artifact@v4
      with:
        name: kleene-daemon
        path: ${{ steps.kleened-pkg-build.outputs.PKG_FILE }}

    - name: Make a new release of Kleened with the builded pkg-package as an asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.kleened-pkg-build.outputs.PKG_FILE }}
