name: Test Release Creation

#on: workflow_dispatch
on:
  workflow_dispatch:
  push:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish an artifact created in FreeBSD to a release
    if: ${{ github.event_name != 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')}}
    env:
      POUDRIERE_JAIL : "14.1-RELEASE"
      MYTOKEN2: "value2"
    permissions:
      # To be able to create releases
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build test-package in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        usesh: true
        run: |
          pwd
          echo "lol" > kleene-daemon-0.1.0.r2.pkg

          mkdir ./kleened-package
          cp ./kleene-daemon-*.pkg ./kleened-package/
          PKG_FILE=$(ls ./kleened-package/)
          PKG_FILE_TRIM=${PKG_FILE%.pkg}
          mv ./kleened-package/${PKG_FILE} ./kleened-package/${PKG_FILE_TRIM}-FreeBSD14.pkg
    - name: Attach package
      run: |
        ls -alh
        pwd
    - name: Test print tags
      run: |
        echo ${{ github.ref }}
        echo ${{ github.ref_type }}
        echo ${{ github.ref_name }}
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./kleened-package/kleene-daemon-*.pkg
